parameters:
#    dj_panel_show.example.class: DjPanel\ShowBundle\Example

services:
#    dj_panel_show.example:
#        class: %dj_panel_show.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
