parameters:
#    dj_panel_main.example.class: DjPanel\MainBundle\Example

services:
#    dj_panel_main.example:
#        class: %dj_panel_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
